DROP DATABASE movies;

CREATE DATABASE movies;

USE movies;

CREATE TABLE movies (
  id INT NOT NULL AUTO_INCREMENT UNIQUE,
  title VARCHAR(255) NOT NULL,
  description VARCHAR (255),
  watched BOOLEAN DEFAULT false,
  PRIMARY KEY(id)
);
